pipeline {
  agent none
  options {
    disableConcurrentBuilds()
    buildDiscarder(logRotator(numToKeepStr: '8', daysToKeepStr: '20'))
    timeout(time: 2, unit: 'HOURS')
  }
  stages {
    stage('build') {
      agent {
        dockerfile {
          dir 'jenkins'
          args '--gpus 1'
        }
      }
      environment {
        HOME = pwd(tmp:true)
        OMP_NUM_THREADS = 4
        project_name = "cshl-vision-2024"
      }
      steps {
        sh 'python3.11 -m venv --system-site-packages $HOME'
        sh '''#!/bin/bash -ex
              source $HOME/bin/activate
              pip install -U pip
              pip install -r requirements.txt
              python3.11 -c "import torch; print(torch.cuda.current_device())"
              cd docs
              make html
           '''
        lock('plenoptic_workshop_publish') {
          sh "docs_dir=\$project_name/pulls/${env.BRANCH_NAME}"
          sh "docs_dir=\${docs_dir/PR-/}"
          sh "commit=\$(git rev-parse HEAD)"
          sh "echo \$(pwd)"
          sh "echo \$(ls docs)"
          sh "echo \$(ls docs/build)"
          git branch: 'main', changelog: false, poll: false, url: 'ssh://git@github.com/plenoptic-org/plenoptic-workshops.git', credentialsId: "ssh"
          sh "echo \$(pwd)"
          sh "rm -rf \$docs_dir"
          sh "mkdir -p \$docs_dir"
          sh "cp -rp \$HOME/docs/build/html/* \$docs_dir"
          sh "echo \$(ls \$docs_dir)"
          // sh "git add -A ${docs_dir}"
          // sh "git commit --author='Flatiron Jenkins <jenkins@flatironinstitute.org>' --allow-empty -m 'Generated documentation for ${docs_dir}' -m '${env.BUILD_TAG} ${commit}'"
          // sh "git push origin main"
        }
      }
    }
  }
  post {
    failure {
      emailext subject: '$PROJECT_NAME - Build #$BUILD_NUMBER - $BUILD_STATUS',
        body: '''$PROJECT_NAME - Build #$BUILD_NUMBER - $BUILD_STATUS

Check console output at $BUILD_URL to view full results.

Building $BRANCH_NAME for $CAUSE
$JOB_DESCRIPTION

Chages:
$CHANGES

End of build log:
${BUILD_LOG,maxLines=200}
''',
	      recipientProviders: [
		    [$class: 'DevelopersRecipientProvider'],
	    ],
	      replyTo: '$DEFAULT_REPLYTO'
    }
  }
}
